.github/workflows/test.yml
tox.ini

It builds the package and check but it is better naming build

[REF] CI: Rename tox check to build

---

.bumpversion.cfg
README.md
setup.py
src/oca_pre_commit_hooks/checks_odoo_module.py
src/oca_pre_commit_hooks/checks_odoo_module_csv.py
src/oca_pre_commit_hooks/checks_odoo_module_po.py
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
src/oca_pre_commit_hooks/cli.py
tests/test_checks.py
tox.ini

* Fix typos
* bump2version: Consider the revision of latest hook version in the README
* README: Small changes
* Remove py3.6 as compatible to match with pre-commit dependency
* Add docstring to checks methods
* Use current path of the file of tests and use os.path.join to avoid mutabling
* Add script to auto generage documentation in README file

[REF] oca_pre_commit_hooks: Small improvements

---

src/oca_pre_commit_hooks/checks_odoo_module_csv.py
src/oca_pre_commit_hooks/checks_odoo_module_po.py
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
src/oca_pre_commit_hooks/utils.py
test_repo/syntax_err_module/__manifest__.py
test_repo/syntax_err_module/i18n/es.po
test_repo/syntax_err_module/ir.model.access.csv
tests/test_checks.py

* PO fix the following error:
```python
pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
Traceback (most recent call last):
File "../polib.py", line 1474, in add
action = getattr(self, 'handle_%s' % next_state)
ResourceWarning: unclosed file <_io.FileIO name='..' mode='rb' closefd=True>
```
* CSV
Add a syntax error CSV file
* ALL
Consider UnicodeDecodeError reading files

[FIX] oca_pre_commit_hooks: Fix checks if it has syntax error

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
test_repo/broken_module/model_view_odoo2.xml
tox.ini

Related to https://github.com/odoo/odoo/pull/103743
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/10

[REF] checks_odoo_module_xml: Allow duplicated fields with 'groups'

---

setup.py
src/oca_pre_commit_hooks/cli.py
src/oca_pre_commit_hooks/cli_po.py
tests/test_checks_po.py

Able to run:
- `src/oca_pre_commit_hooks/cli_po.py --help`
- `src/oca_pre_commit_hooks/cli.py --help`

[REF] oca_pre_commit_hooks: Separate files cli and cli_po to run it directly

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module.py
src/oca_pre_commit_hooks/checks_odoo_module_csv.py
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
src/oca_pre_commit_hooks/utils.py
test_repo/broken_module/__openerp__.py
test_repo/broken_module/skip_file_no_used.xml
test_repo/broken_module/skip_file_not_used.xml
test_repo/broken_module/skip_xml_check.xml
test_repo/broken_module/skip_xml_check_2.xml
test_repo/broken_module/skip_xml_check_3.xml
test_repo/broken_module/template1_disable.xml
test_repo/test_module/__openerp__.py
test_repo/test_module/website_templates_disable.xml
tests/common.py
tests/test_checks.py
tox.ini

Add support to disable checks for XML files based on comments
e.g.
```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
...
</odoo>
```
In this case the check `xml-deprecated-openerp-node` will be disabled only for this file
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/40

[IMP] oca_pre_commit_hooks: Support disable XML checks from disable comments

---

README.md
src/oca_pre_commit_hooks/cli.py
src/oca_pre_commit_hooks/cli_po.py
src/oca_pre_commit_hooks/global_parser.py
src/oca_pre_commit_hooks/utils.py
tests/common.py

Fixes #37 
Argument parser was subclassed in order to hook into the `parse_args` method without disrupting the existing code flow. All code downstream does not even know of the existence of a config file and just gets the `enable`, `disable` options as they did before.

Draft: [IMP] oca_pre_commit_hooks: Support for config file (#37)

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module.py
src/oca_pre_commit_hooks/checks_odoo_module_po.py
src/oca_pre_commit_hooks/global_parser.py
src/oca_pre_commit_hooks/utils.py
tests/common.py
tests/test_checks.py
tests/test_checks_po.py

Fixes #44 
Calling entry points with the argument `--list-msgs` prints out a list of all enabled messages.

[IMP] oca_pre_commit_hooks: Add --list-msgs option (#44)

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module.py
test_repo/broken_module/__openerp__.py
test_repo/broken_module/template1_copy2.xml
tests/test_checks.py

"qweb" is compatible using glob expressions from the manifest data file
It was raising xml-syntax-error because the file was not found
Something like:
module/static/src/xml/*.xml:1 [Errno 2] No such file or directory: '' - []
It was fixed using processing the glob expression but qweb is not using the module name as prefix

[FIX] checks_odoo_module: Support glob expression for "qweb" manifest data section

---

src/oca_pre_commit_hooks/checks_odoo_module_xml.py
test_repo/broken_module/model_view.xml

Use of translatable xpath `text()` - [xml-xpath-translatable-item]

[FIX] xml-xpath-translatable-item: Fix false negative calling a method `o.amount_to_text()`

---

src/oca_pre_commit_hooks/checks_odoo_module_xml.py
src/oca_pre_commit_hooks/utils.py
test_repo/broken_module/__openerp__.py
test_repo/broken_module/deprecated_disable.xml

Fixes #59 and prints out a deprecated warning with the offending line for every file which uses this **deprecated** method of disabling hooks.

[REF] hooks: Add support for <!-- pylint:disable=CHECK -->

---

.github/workflows/test.yml
.pre-commit-config.yaml
tox.ini

Repository was moved from gitlab to github. This fixes `tox -e lint` which as of right now hangs indefinitely (asks username for gitlab.com).

[FIX] ci: update flake8 repo URL, tox.ini and gh actions .yml

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_xml.py

Replacing elements is by nature unsafe since xpaths in other views may reference the element. Other methods should be tried first, this information has been added to the error message generated by this check to help users.

[IMP] Help msg for "xml-view-dangerous-replace-low-priority"

---

README.md
src/oca_pre_commit_hooks/global_parser.py
tests/test_checks.py
tests/test_checks_po.py

Fix #37 
The README has been modified to include documentation on how to use the configuration file (.oca_hooks.cfg) to enable/disable messages.
The help message for the config file now includes info on the default lookup location as well.

[IMP] README: Added a section on configuration (#37)

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
test_repo/test_module/website_templates.xml
tests/test_checks.py

Closes #27.
This checks generates a message whenever a tag with 'oe_structure' in its classes has no id attribute.

[IMP] add xml-oe-structure-missing-id check

---

.github/workflows/test.yml
README.md
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
tests/test_checks.py
tests/test_profiling.py
tox.ini

Added simple profiling test cases to get insights into the program
flow and possible bottlenecks of the system. The profiling
can be done on user-repositories with the following command:
`PROFILING_TEST_REPO=path/to/repo tox -e cprofile`
--------
* Some XPath expressions were improved to offload work from python code
* Similar to regex, xpath expressions are compiled at the class level and
reused by checks, this means they are only compiled once instead of
multiple times. More info:https://lxml.de/xpathxslt.html#the-xpath-class
* There was a false negative in test_repo/broken_module/skip_xml_check2.xml:3,
xml-data-deprecated-node should be raised but was not, this was discovered
when improving the xpath expressions. Apparently the previous method
(using iterchildren) also counted comments …

[REF] improve XPath expressions, compile them only once, fix false negative

---

README.md
docs/conf.py
docs/index.rst
docs/messages/index.rst
docs/messages/xml/index.rst
docs/messages/xml/oe-structure-missing-id.rst
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
test_repo/test_module/website_templates.xml
test_repo/test_module/website_templates_disable.xml
tests/test_checks.py

Related to https://github.com/OCA/odoo-pre-commit-hooks/issues/27.
The lint will now trigger on elements with an invalid id. For odoo
to consider it, the id must contain oe_structure. (See link below).
https://github.com/odoo/odoo/blob/25edcc89273c389f318c434ce9a9e0b531b8e599/addons/web_editor/models/ir_ui_view.py#L41
Aditionally documentation for in-depth explanation on this hook has been
added.

[FIX] oe-structure-missing-id: change constraints, add docs

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
test_repo/broken_module/model_view.xml
tests/test_checks.py

Closes #63.
This adds a new check for records that don't have an xmlid. It reuses the existing loop that goes over all records in the XML file to find records without an id.

[IMP] add xml-record-missing-id

---

src/oca_pre_commit_hooks/base_checker.py
src/oca_pre_commit_hooks/checks_odoo_module.py
src/oca_pre_commit_hooks/checks_odoo_module_csv.py
src/oca_pre_commit_hooks/checks_odoo_module_po.py
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
src/oca_pre_commit_hooks/utils.py

Related to #77.
* Messages are no longer filtered out. Instead they are not generated in the first place. This prevents subtle bugs from being introduced, where a check is run (unwanted) and no one notices it because its messages are filtered out. It also simplifies the program's flow and avoids useless execution.
* is_message_enabled has been moved to BaseChecker, this makes code easier and removes redundancy since the same enable, disable sets were being passed around constantly.

[REF] Don't filter out messages, move is_message_enabled

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
test_repo/broken_module/template1.xml
tests/common.py
tests/test_checks.py

Fixes #28.
This adds a new message for xml files which detects duplicate ids found in templates (<template> tag).

Draft: [IMP] add xml-duplicate-template-id message

---

.github/workflows/test.yml
setup.py

- Re-enable py3.11 windows build
- Remove duplicated included build py-3.10
- Split builds for lint, docs and build in order to improve detection of errors

[REF] setup: Enable py311 classifier (#117)

---

.github/workflows/test.yml
setup.py
tox.ini

1. Changelog is now being generated. This can be verified by running `tox -e build` and untarring the resulting files in `dist/`
2. actions/checkout@v2 was deprecated and emitting warnings, therefore it has been updated.

CI improvements

---

.github/workflows/test.yml
pyproject.toml
test-requirements.txt

Related to https://github.com/actions/setup-python/issues/825\#issuecomment-2096792396

[REF] github-actions: Use macosx-latest only for py-latest and macosx-14 for older

---

README.md
src/oca_pre_commit_hooks/base_checker.py
test_repo/broken_module/skip_xml_check_3.xml
tests/test_checks.py

If some checks were disabled inline on a file, the global disabled checks were ignored and possibly executed.
This is likely a regression since d7753c87, where the `is_message_enabled` was refactorized and this condition was changed.

[FIX] unwanted execution of globally disabled checks

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_po.py

Extract the line number from the error message, strip it away from the
string and pass it to the error printing function
Fix #107
Note: although I target the main branch, I based this on the following PR https://github.com/OCA/odoo-pre-commit-hooks/pull/106

[IMP] check_odoo_module_po: extract line number from error message

---

src/oca_pre_commit_hooks/base_checker.py
src/oca_pre_commit_hooks/checks_odoo_module.py
src/oca_pre_commit_hooks/checks_odoo_module_csv.py
src/oca_pre_commit_hooks/checks_odoo_module_po.py
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
tests/test_checks.py
tests/test_checks_po.py

Hello @moylop260 ,
Here's a proposal to display the duplicated lines and the extra information that was once displayed before the colored output refactor.
Followup of the discussion in:
- https://github.com/OCA/odoo-pre-commit-hooks/pull/109
**Example output:**

[IMP] Print extra information

---

src/oca_pre_commit_hooks/checks_odoo_module_po.py
test_repo/test_module/i18n_extra/fr.po

Autofix is empty the translations where the original term is the same than translated one
e.g.
msgid "CRM"
msgstr "CRM"  --> ""
However, there are valid cases to reset the translated value
But it should be only for i18n_extra folder
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/100

[FIX] po-pretty-format: Allow original=translate term  for "i18n_extra" folder

---

.github/workflows/test.yml
README.md
setup.py
tox.ini

python3.8 is obsolote and OS are removing old python version
e.g. ubuntu-latest (24.04) is not available to install py3.8-
and github actions are using this OS version
Also, other packages are removing support for py3.8-
e.g. pylint
[REF] github-actions: Use new py3.13
[REF] tox: update-readme force to use new py3.13 instead of py3.10

[REF] setup.py: Deprecate py3.8- and use new py3.13

---

src/oca_pre_commit_hooks/checks_odoo_module_po.py

You can reproduce it using github actions:
```yaml
name: Reproduce UnicodeEncodeError
on:
push:
branches:
- main
jobs:
test-py-wo-fix:
runs-on: windows-latest
steps:
- name: Checkout code
uses: actions/checkout@v3
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.11'
- name: Force cp1252 encoding
run: |
chcp 1252
echo "PYTHONIOENCODING=cp1252" >> $GITHUB_ENV
- name: Run Python script
run: |
python -c "print('Fixing example ⚒')"
```
Note: I could not reproduce it using "tox" so it was not added to our unittest
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/95

[REF] checks_odoo_module_po: Remove special char incompatible with windows codecs

---

README.md
src/oca_pre_commit_hooks/checks_odoo_module_po.py
test_repo/broken_module/i18n_extra/es.po

Odoo exports translations grouped by "msgid" and it deletes duplicated
if you will not use odoo exports feature so you will need to manage manually the po file and use duplicated "msgid"
Manual PO files should be located in i18n_extra folder
This commit ignores this check for this extra folder
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/122

[REF] po-duplicate-message-definition: Ignore i18n_extra folder

---

README.md
src/oca_pre_commit_hooks/base_checker.py
src/oca_pre_commit_hooks/checks_odoo_module.py
src/oca_pre_commit_hooks/checks_odoo_module_xml.py
src/oca_pre_commit_hooks/utils.py
test_repo/broken_module/model_view.xml
test_repo/odoo18_module/__manifest__.py
test_repo/odoo18_module/views/deprecated_chatter.xml
tests/test_checks.py

A new check has been added to check for deprecated chatters in modules version 18 and above. For this new check it was also necessary to extract module version in order to selectively enable/disable the new check.
Closes #121.

[IMP] deprecated_chatter check for >= v18
